site_name: Battlefront+
theme:
  name: material
  logo: assets/bfplus-logo.svg
  favicon: assets/bfplus-rexlogo.png
  palette:
    scheme: slate
    primary: custom
    accent: orange
  font:
    text: Poppins
  features:
    - navigation.expand
  icon:
    repo: octicons/download-24
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
  - footnotes
  - toc:
      toc_depth: 3
hooks:
  - 'docs/details/toc.py'
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
       - no-lb
      auto_caption: false
      caption_position: bottom
  - mkdocs-video
extra:
  generator: false
  analytics:
    provider: google 
    property: G-6H10EQ2QT0 
  social:
    - icon: fontawesome/solid/folder-plus
      link: https://www.nexusmods.com/starwarsbattlefront22017/mods/7592 
      name: Download BF+
    - icon: fontawesome/brands/discord  
      link: https://discord.gg/99VtTgFBqq 
      name: Discord
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/extra.js

repo_url: https://www.nexusmods.com/starwarsbattlefront22017/mods/7592 
repo_name: Download on NexusMods
  
copyright: Battlefront+ Team 

nav:
  - Overview: 'index.md'
  - Gallery: 'gallery.md'
  - Details:
    - 'details/heroes.md'
    - 'details/reinforcements.md'
    - 'details/blasters.md'
    - 'details/starcards.md'
    - 'details/appearances.md'
    - 'details/gamemodes.md'
  - Setup:
    - 'setup/installation.md'
    - 'setup/troubleshooting.md'
  - Community Updates:
    - 'community-updates/v9.md'
    - 'community-updates/v8.md'