site_name: Battlefront+
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: orange
  font:
    text: Poppins
  features:
    - navigation.expand
  icon:
    repo: octicons/download-24
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
       - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - mkdocs-video
extra:
  generator: false
  social:
    - icon: fontawesome/solid/folder-plus
      link: https://www.nexusmods.com/starwarsbattlefront22017/mods/7592 
      name: Download BF+
    - icon: fontawesome/brands/discord  
      link: https://discord.gg/99VtTgFBqq 
      name: Discord
extra_css:
  - stylesheets/extra.css

repo_url: https://www.nexusmods.com/starwarsbattlefront22017/mods/7592 
repo_name: Download on NexusMods
  
copyright: Battlefront+ Team 

nav:
  - Overview: 'index.md'
  - Gallery: 'gallery.md'
  - Installation: 'installation.md'
  - Details:
    - 'content/heroes.md'
    - 'content/reinforcements.md'
    - 'content/troopers.md'
  - Changelog: 'changes.md'
  - Troubleshooting:
    - 'troubleshooting/compatibility.md'