site_name: Battlefront+
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: orange
  font:
    text: Poppins
  features:
    - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
       - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - mkdocs-video

nav:
  - Overview: 'index.md'
  - Installation: 'installation.md'
  - Details:
    - 'content/heroes.md'
    - 'content/reinforcements.md'
    - 'content/troopers.md'
  - Changelog: 'changes.md'